### ISSUE TITLE
Ppoblems getting this to work

### ISSUE THREAD

**Issue by Hogflash** [theodore-s-beers/pdfo#30]
Theo, I've tries implementing this and I am unable to get it to work at all.  I'm not sure what I am doing wrong here.  I've tried following the exact same method that worked fine with PDFObject, but no success.  Also tried using this method (where pdfo.js is the sample.pdfo.min.js code)

<script> <br />
import * as pdfo from '/js-dev/pdfobject/pdfo.js'  <br />
//const pdfOptions = { fallbackPrefix: 'https://docs.google.com/viewer?embedded=true&url=' };  <br />
pdfo.embed('https://www.azbodydance.com/schedules/current/sched-jan23-v1.pdf', '#sched_current');  <br />
</script> <br /> <br />

Any suggestions?

**Comment by theodore-s-beers** [comment]
I use pdfo with a bundler. If you want to use it directly, like how PDFObject works, see the `pdfo.min.js` file that I just added to the repo. Below is a minimal working example of what you would need to do in HTML.

This assumes that `pdfo.min.js` is in the same directory as the HTML file, but of course you could change that. Also note the `type="module"` attribute on the `<script>` tag. It should work in all modern browsers.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script type="module">
      import * as pdfo from "./pdfo.min.js";
      pdfo.embed(
        "https://www.azbodydance.com/schedules/current/sched-jan23-v1.pdf",
        "#pdf-box"
      );
    </script>
    <title>pdfo demo</title>
  </head>
  <body style="max-width: 72rem; margin: 0 auto; padding: 1rem">
    <div id="pdf-box" style="height: 80vh"></div>
  </body>
</html>
```

**Comment by Hogflash** [comment]
Theo, It works perfectly now!  I tested it on Win10-Edge  109.0.1518.52 and
on iPhone Safari 16.1.1.  I also tried passing pdfOpenParams: {view:
'fitH'} and that also worked without any issues.

Only thing I run into occasionally is Google occasionally does not respond
and the page needs to be refreshed to display the PDF.  Not a pdfo issue!

Regards,

Gary
